### ISSUE TITLE
Suggested minor changes for the Readme.md file

### ISSUE THREAD

**Issue by andyburnett** [wpilibsuite/xrp-wpilib-firmware#28]
I have a couple of quick suggestions:

> While holding the BOOTSEL button (the white button on the green Pico W, near the USB connector), quickly press the reset button (middle left side of the XRP board), and then release the BOOTSEL button

I could not get this to work. However, unplugging the usb cable, holding down the BOOTSEL button, whilst plugging the cable back into the computer did work. Perhaps that is the safer instruction.

> The board will temporariloy disconnect from your computer, and then reconnect as a USB storage device named "RPI-RP2"

Typo temporarily.

**Comment by zhiquanyeo** [comment]
Ah yeah, i think the instruction there should be "'press and release the reset button' while holding the BOOTSEL button. After this, release the BOOTSEL button"

**Comment by andyburnett** [comment]
Well, the strange thing is that I did try doing exactly what you have written, it’s just that I couldn’t get that to work. However, the process (which is described on the Raspberry pi site), of holding down BOOTSEL, and then plugging in the USB cable did work. 

Perhaps it is worth adding a note to that effect. It is possible that there is something wrong with my board, and that the original instructions will work for others.

**Comment by zhiquanyeo** [comment]
Updated the README with this note
