### ISSUE TITLE
Unable to connect to network when pw changed

### ISSUE THREAD

**Issue by NoahRen25** [wpilibsuite/xrp-wpilib-firmware#32]
I think this is an issue of making the password too short (I changed it to a 4 character password), and now I can't connect to it.

I don't have a way to access the json file to change it back, and I tried re-downloading the firmware, along with accessing the local port after plugging in my computer. However, none of these things worked.

I could be missing a way for sure, but is there another way to change the password or reset it?

Otherwise, I think it could be helpful to add something related to this in the README.

Thanks!

P.S. The software works great otherwise! :)

**Comment by jpokornyiii** [comment]
If it fails to connect via the network it should fall back to AP mode. Did you try opening: http://192.168.42.1:5000 in your browser to see if it loads (should show the JSON file)? Note you have to connect to the AP that is XRP-<IDENT> with password xrp-wpilib. More details here: https://docs.wpilib.org/en/latest/docs/xrp-robot/hardware-and-imaging.html

If this doesn't work, I suggest nuking the PICO and re-uploading the firmware. This should wipe out the JSON file.

Use this flash nuke firmware here:
https://learn.adafruit.com/getting-started-with-raspberry-pi-pico-circuitpython/circuitpython

Let me know how it goes.

**Comment by NoahRen25** [comment]
Hello,
The initial problem was that I was unable to connect to it after changing the password (it was too short) - That is I had connected earlier and changed it in the JSON, but wasn't able to change it back as I couldn't connect to it.

With that being said, after using the flash nuke firmware and re-installing it, it worked.

Thank you so much!

**Comment by zhiquanyeo** [comment]
Re-opening this. We'll add a check on the web UI side to ensure minimum password length
